### ISSUE TITLE
objectsore issue with fresh installation

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/wok#13]
platform: s390x, os: KVM for IBM z Systems
steps:
installed os freshly, installed dependencies and installed wok, ginger, gingerbase and gingers390x via git clone, autogen, make and make install.

logged in from ui and got below error when loading "Administration" tab.
![screenshot from 2015-12-30 16 09 05](https://cloud.githubusercontent.com/assets/12499230/12049685/557b7b8a-af10-11e5-8a93-e6603fa90615.png)

log captured:

[30/Dec/2015:11:34:26] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 351, in index
    return self.get(filter_params)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 338, in get
    resources = self._get_resources(flag_filter)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 295, in _get_resources
    idents = get_list(*self.model_args, **flag_filter)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/backup.py", line 202, in get_list
    return self._session_get_list(session)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/backup.py", line 198, in _session_get_list
    return session.get_list(self._objstore_type, sort_key='timestamp')
  File "/usr/lib/python2.7/site-packages/wok/objectstore.py", line 48, in get_list
    ids = self._get_list(obj_type)
  File "/usr/lib/python2.7/site-packages/wok/objectstore.py", line 44, in _get_list
    res = c.execute('SELECT id FROM objects WHERE type=?', (obj_type,))
OperationalError: no such table: objects

looks like some select statement is executed on empty objectstore db

**Comment by pvital** [comment]
Please, paste the ouput of the following commands using the Ginger objectstore.

```
$ sudo sqlite3 <path_to_the>/objectstore_ginger
SQLite version 3.9.2 2015-11-02 18:31:45
Enter ".help" for usage hints.
sqlite> .tables
objects
sqlite> .schema
CREATE TABLE objects
                (id TEXT, type TEXT, json TEXT, version TEXT, PRIMARY KEY (id, type));
sqlite> SELECT * FROM objects;
```

**Comment by sureshab** [comment]
[root@zfwcec164 wok]# pwd
/var/lib/wok
[root@zfwcec164 wok]# sqlite3 objectstore_ginger 
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
COMMIT;
sqlite> .tables
sqlite> .schema
sqlite> .quit
[root@zfwcec164 wok]

**Comment by pvital** [comment]
This issue can be closed. The objectstore file used by Ginger plugin is now updated and the error is not present anymore.

Below is the output of the sqlite commands used to check the file in a Ubuntu 15.10 system with upstream code from Wok and Ginger.
```
test@ubuntu:~/wok/data$ sudo sqlite3 objectstore_ginger
SQLite version 3.8.11.1 2015-07-29 20:00:57
Enter ".help" for usage hints.
sqlite> .tables
objects
sqlite> .schema
CREATE TABLE objects
                      (id TEXT, type TEXT, json TEXT, version TEXT,
                      PRIMARY KEY (id, type));
sqlite>
```

If the issue persist, please open a new one on Ginger project.
