### ISSUE TITLE
Nginx patch is breaking the unit tests of WoK plug-ins

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/wok#153]
After commit 4cbb1b9 unit tests of Gingerbase, Ginger and Kimchi started failing with the same error message:

```
Traceback (most recent call last):
  File "test_host.py", line 60, in setUpModule
    cherrypy_port=cherrypy_port, model=model)
  File "/home/danielhb/kimchi/wok_all_plugins/tests/utils.py", line 127, in run_server
    s = wok.server.Server(args)
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/server.py", line 77, in __init__
    start_proxy(options)
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/proxy.py", line 126, in start_proxy
    _create_proxy_config(options)
  File "/home/danielhb/kimchi/wok_all_plugins/src/wok/proxy.py", line 118, in _create_proxy_config
    dst = os.path.join(paths.sys_nginx_conf_dir, "wok.conf")
AttributeError: 'Paths' object has no attribute 'sys_nginx_conf_dir'

```

**Comment by pvital** [comment]
You need to rebuild wok to update src/wok/wok/config.py that has this new variable.

**Comment by danielhb** [comment]
Yeah I got careless and forgot to run build.all. Rookie mistake :(
