### ISSUE TITLE
wok is pointing to /etc/nginx/conf.d which does not exists on OpenSuse 42.1

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/wok#166]
After fresh opensuse 42.1 fresh install, run make check

notice:
```
======================================================================
ERROR: setUpModule (test_api)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_api.py", line 43, in setUpModule
    test_server = utils.run_server(host, port, ssl_port, test_mode=True)
  File "utils.py", line 127, in run_server
    s = wok.server.Server(args)
  File "/root/WOK/src/wok/server.py", line 77, in __init__
    start_proxy(options)
  File "/root/WOK/src/wok/proxy.py", line 126, in start_proxy
    _create_proxy_config(options)
  File "/root/WOK/src/wok/proxy.py", line 121, in _create_proxy_config
    os.symlink(os.path.join(nginx_config_dir, "wok.conf"), dst)
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: test_development_env (test_exception.ExceptionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exception.py", line 96, in test_development_env
    setup_server()
  File "test_exception.py", line 43, in setup_server
    environment=environment)
  File "utils.py", line 127, in run_server
    s = wok.server.Server(args)
  File "/root/WOK/src/wok/server.py", line 77, in __init__
    start_proxy(options)
  File "/root/WOK/src/wok/proxy.py", line 126, in start_proxy
    _create_proxy_config(options)
  File "/root/WOK/src/wok/proxy.py", line 121, in _create_proxy_config
    os.symlink(os.path.join(nginx_config_dir, "wok.conf"), dst)
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: test_development_env (test_exception.ExceptionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exception.py", line 48, in tearDown
    test_server.stop()
AttributeError: 'NoneType' object has no attribute 'stop'

======================================================================
ERROR: test_production_env (test_exception.ExceptionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exception.py", line 54, in test_production_env
    setup_server('production')
  File "test_exception.py", line 43, in setup_server
    environment=environment)
  File "utils.py", line 127, in run_server
    s = wok.server.Server(args)
  File "/root/WOK/src/wok/server.py", line 77, in __init__
    start_proxy(options)
  File "/root/WOK/src/wok/proxy.py", line 126, in start_proxy
    _create_proxy_config(options)
  File "/root/WOK/src/wok/proxy.py", line 121, in _create_proxy_config
    os.symlink(os.path.join(nginx_config_dir, "wok.conf"), dst)
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: test_production_env (test_exception.ExceptionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exception.py", line 48, in tearDown
    test_server.stop()
AttributeError: 'NoneType' object has no attribute 'stop'

======================================================================
ERROR: setUpModule (test_plugin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_plugin.py", line 45, in setUpModule
    test_server = utils.run_server(host, port, ssl_port, test_mode=True)
  File "utils.py", line 127, in run_server
    s = wok.server.Server(args)
  File "/root/WOK/src/wok/server.py", line 77, in __init__
    start_proxy(options)
  File "/root/WOK/src/wok/proxy.py", line 126, in start_proxy
    _create_proxy_config(options)
  File "/root/WOK/src/wok/proxy.py", line 121, in _create_proxy_config
    os.symlink(os.path.join(nginx_config_dir, "wok.conf"), dst)
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: setUpModule (test_server)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_server.py", line 54, in setUpModule
    cherrypy_port=cherrypy_port)
  File "utils.py", line 127, in run_server
    s = wok.server.Server(args)
  File "/root/WOK/src/wok/server.py", line 77, in __init__
    start_proxy(options)
  File "/root/WOK/src/wok/proxy.py", line 126, in start_proxy
    _create_proxy_config(options)
  File "/root/WOK/src/wok/proxy.py", line 121, in _create_proxy_config
    os.symlink(os.path.join(nginx_config_dir, "wok.conf"), dst)
OSError: [Errno 2] No such file or directory
```

Output of rpm -ql nginx:
```
linux-bdc7:~/WOK # rpm -ql nginx
/etc/logrotate.d/nginx
/etc/nginx
/etc/nginx/fastcgi.conf
/etc/nginx/fastcgi.conf.default
/etc/nginx/fastcgi_params
/etc/nginx/fastcgi_params.default
/etc/nginx/koi-utf
/etc/nginx/koi-win
/etc/nginx/mime.types
/etc/nginx/mime.types.default
/etc/nginx/nginx.conf
/etc/nginx/nginx.conf.default
/etc/nginx/scgi_params
/etc/nginx/scgi_params.default
/etc/nginx/uwsgi_params
/etc/nginx/uwsgi_params.default
/etc/nginx/win-utf
/srv/www/htdocs/50x.html
/usr/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi/auto/nginx
/usr/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi/auto/nginx/nginx.bs
/usr/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi/auto/nginx/nginx.so
/usr/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi/nginx.pm
/usr/lib/systemd/system/nginx.service
/usr/sbin/nginx
/usr/sbin/rcnginx
/usr/share/doc/packages/nginx
/usr/share/doc/packages/nginx/CHANGES
/usr/share/doc/packages/nginx/CHANGES.ru
/usr/share/doc/packages/nginx/conf
/usr/share/doc/packages/nginx/conf/fastcgi.conf
/usr/share/doc/packages/nginx/conf/fastcgi_params
/usr/share/doc/packages/nginx/conf/koi-utf
/usr/share/doc/packages/nginx/conf/koi-win
/usr/share/doc/packages/nginx/conf/mime.types
/usr/share/doc/packages/nginx/conf/nginx.conf
/usr/share/doc/packages/nginx/conf/scgi_params
/usr/share/doc/packages/nginx/conf/uwsgi_params
/usr/share/doc/packages/nginx/conf/win-utf
/usr/share/doc/packages/nginx/contrib
/usr/share/doc/packages/nginx/contrib/README
/usr/share/doc/packages/nginx/contrib/geo2nginx.pl
/usr/share/doc/packages/nginx/contrib/unicode2nginx
/usr/share/doc/packages/nginx/contrib/unicode2nginx/koi-utf
/usr/share/doc/packages/nginx/contrib/unicode2nginx/unicode-to-nginx.pl
/usr/share/doc/packages/nginx/contrib/unicode2nginx/win-utf
/usr/share/doc/packages/nginx/contrib/vim
/usr/share/doc/packages/nginx/contrib/vim/ftdetect
/usr/share/doc/packages/nginx/contrib/vim/ftdetect/nginx.vim
/usr/share/doc/packages/nginx/contrib/vim/indent
/usr/share/doc/packages/nginx/contrib/vim/indent/nginx.vim
/usr/share/doc/packages/nginx/contrib/vim/syntax
/usr/share/doc/packages/nginx/contrib/vim/syntax/nginx.vim
/usr/share/doc/packages/nginx/ngx-fancyindex-0.3.5
/usr/share/doc/packages/nginx/ngx-fancyindex-0.3.5/LICENSE
/usr/share/doc/packages/nginx/ngx-fancyindex-0.3.5/README.rst
/usr/share/doc/packages/nginx/ngx-fancyindex-0.3.5/template.awk
/usr/share/doc/packages/nginx/ngx-fancyindex-0.3.5/template.h
/usr/share/doc/packages/nginx/ngx-fancyindex-0.3.5/template.html
/usr/share/man/man3/nginx.3pm.gz
/var/lib/nginx
/var/lib/nginx/fastcgi
/var/lib/nginx/proxy
/var/lib/nginx/scgi
/var/lib/nginx/tmp
/var/lib/nginx/uwsgi
/var/log/nginx
```

**Comment by alinefm** [comment]
Hi @ramonmedeiros 
Is it only a make-check issue or you see the same problem running the server on production/dev mode?

**Comment by ramonmedeiros** [comment]
Hi @alinefm,

this happened on a production environment. As i pointed above, /etc/nginx/conf.d does not come with rpm, and kimchi is not dealing with this, creating the directory. Can i send a patch?

**Comment by alinefm** [comment]
Sure, please send a patch. I will assign this issue to you.
