### ISSUE TITLE
Error shown on user activity log of Settings tab

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/wok#171]
I am seeing the following error on s390x environment always:

[root@zfwcec215 wok]# uname -a
Linux zfwcec215 4.4.0-37.56.el7_2.kvmibm1_1_3.2.s390x #1 SMP Sat Sep 24 03:41:59 EDT 2016 s390x s390x s390x GNU/Linux

<img width="1278" alt="screen shot 2016-09-28 at 5 39 28 pm" src="https://cloud.githubusercontent.com/assets/10830725/18912967/d86a22d0-85a2-11e6-9390-ea6cb7667db4.png">

[28/Sep/2016:14:07:30] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 442, in index
    return self.get(params)
  File "/usr/lib/python2.7/site-packages/wok/control/logs.py", line 39, in get
    res_list = get_list(filter_params)
  File "/usr/lib/python2.7/site-packages/wok/model/logs.py", line 31, in get_list
    return RequestParser().getRecords()
  File "/usr/lib/python2.7/site-packages/wok/reqlogger.py", line 206, in getRecords
    text = self.getTranslatedMessage(message, error, uri)
  File "/usr/lib/python2.7/site-packages/wok/reqlogger.py", line 175, in getTranslatedMessage
    text = msg.get_text(prepend_code=False, translate=True)
  File "/usr/lib/python2.7/site-packages/wok/message.py", line 89, in get_text
    msg = decode_value(msg) % self.args
KeyError: u'name'

[28/Sep/2016:14:07:45] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 442, in index
    return self.get(params)
  File "/usr/lib/python2.7/site-packages/wok/control/logs.py", line 39, in get
    res_list = get_list(filter_params)
  File "/usr/lib/python2.7/site-packages/wok/model/logs.py", line 31, in get_list
    return RequestParser().getRecords()
  File "/usr/lib/python2.7/site-packages/wok/reqlogger.py", line 206, in getRecords
    text = self.getTranslatedMessage(message, error, uri)
  File "/usr/lib/python2.7/site-packages/wok/reqlogger.py", line 175, in getTranslatedMessage
    text = msg.get_text(prepend_code=False, translate=True)
  File "/usr/lib/python2.7/site-packages/wok/message.py", line 89, in get_text
    msg = decode_value(msg) % self.args
KeyError: u'name'

**Comment by alinefm** [comment]
Hi @chandrureddy 

I don't have a s390x system to verify this issue. Does it only happen on s390x?

**Comment by alinefm** [comment]
Fixed by dcdf104eeb7706059b85a904ce7d1e7bd2481800
