### ISSUE TITLE
Exception: No common user found

### ISSUE THREAD

**Issue by itJunky** [kimchi-project/wok#172]
After install all dependency and run wokd i getting error:

# wokd 
Traceback (most recent call last):
  File "/usr/bin/wokd", line 109, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/wokd", line 106, in main
    wok.server.main(options)
  File "/usr/lib/python2.6/site-packages/wok/server.py", line 247, in main
    srv = Server(options)
  File "/usr/lib/python2.6/site-packages/wok/server.py", line 77, in __init__
    start_proxy(options)
  File "/usr/lib/python2.6/site-packages/wok/proxy.py", line 133, in start_proxy
    _create_proxy_config(options)
  File "/usr/lib/python2.6/site-packages/wok/proxy.py", line 64, in _create_proxy_config
    raise Exception("No common user found")
Exception: No common user found

**Comment by alinefm** [comment]
Hi @itJunky 

Which wok version are you using?
Have you run wokd as root? Is the nginx service running?
