### ISSUE TITLE
Cannot LDAP authentication as admin 

### ISSUE THREAD

**Issue by biancafc** [kimchi-project/wok#208]
Cent OS 7
I'm getting the error: The server encountered an unexpected condition which prevented it from fulfilling the request.

Error in wok logs:

```
[13/Mar/2017:15:00:49] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/root.py", line 207, in login
    user_info = auth.login(username, password)
  File "/usr/lib/python2.7/site-packages/wok/auth.py", line 302, in login
    user = User.get(auth_args)
  File "/usr/lib/python2.7/site-packages/wok/auth.py", line 86, in get
    return klass(auth_args['username'])
  File "/usr/lib/python2.7/site-packages/wok/auth.py", line 195, in __init__
    super(PAMUser, self).__init__(username)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by biancafc** [comment]
Duplicate of https://github.com/kimchi-project/wok/issues/207
