### ISSUE TITLE
make check/run_tests.sh fails in Opensuse Leap 42.2 with sudo

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/wok#209]
```
======================================================================
FAIL: test_wok_config (test_config.ConfigTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_config.py", line 229, in test_wok_config
    self.assertEquals(wok_config, configObj)
AssertionError: {'/wok-ui.html': {'tools.wokauth.on': True}, '/libs': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticdir.dir': '/home/danielhb/wok/ui/libs', 'tools.expires.on': True, 'tools.expires.secs': 31536000, 'tools.staticdir.on': True}, '/favicon.ico': {'tools.staticfile.on': True, 'tools.staticfile.filename': '/home/danielhb/wok/ui/images/logo.ico'}, '/data/logs': {'tools.wokauth.on': True, 'tools.nocache.on': False, 'tools.staticdir.dir': '/home/danielhb/wok/data/logs', 'tools.staticdir.on': True}, '/images': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticdir.dir': '/home/danielhb/wok/ui/images', 'tools.staticdir.on': True}, '/fonts/OpenSans-LightItalic.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype/OpenSans-LightItalic.ttf'}, '/base64/jquery.base64.js': {'tools.nocache.on': True, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/home/danielhb/wok/ui/base64/jquery.base64.js'}, '/fonts/OpenSans-Bold.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype/OpenSans-Bold.ttf'}, '/fonts/OpenSans-Italic.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype/OpenSans-Italic.ttf'}, '/fonts/OpenSans-Semibold.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype/OpenSans-Semibold.ttf'}, '/fonts/fontawesome-webfont.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype/fontawesome-webfont.ttf'}, '/ui/config/tab-ext.xml': {'tools.nocache.on': True, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/home/danielhb/wok/ui/config/tab-ext.xml'}, '/css': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticdir.dir': '/home/danielhb/wok/ui/css', 'tools.expires.on': True, 'tools.expires.secs': 31536000, 'tools.staticdir.on': True}, '/robots.txt': {'tools.staticfile.on': True, 'tools.staticfile.filename': '/home/danielhb/wok/ui/robots.txt'}, '/js': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticdir.dir': '/home/danielhb/wok/ui/js', 'tools.expires.on': True, 'tools.expires.secs': 31536000, 'tools.staticdir.on': True}, '/help': {'tools.nocache.on': True, 'tools.staticdir.dir': '/home/danielhb/wok/ui/pages/help', 'tools.staticdir.on': True}, '/fonts/OpenSans-Light.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype/OpenSans-Light.ttf'}, '/': {'request.methods_with_bodies': ('POST', 'PUT'), 'tools.sessions.name': 'wok', 'tools.proxy.on': True, 'tools.sessions.locking': 'explicit', 'tools.sessions.httponly': True, 'tools.sessions.storage_type': 'ram', 'tools.sessions.on': True, 'tools.sessions.secure': True, 'tools.wokauth.on': False, 'tools.nocache.on': True, 'tools.trailing_slash.on': False}, '/fonts/OpenSans-SemiboldItalic.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype/OpenSans-SemiboldItalic.ttf'}, '/fonts/OpenSans-ExtraBold.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype/OpenSans-ExtraBold.ttf'}, '/fonts/OpenSans-BoldItalic.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype/OpenSans-BoldItalic.ttf'}, '/fonts/OpenSans-ExtraBoldItalic.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype/OpenSans-ExtraBoldItalic.ttf'}, '/fonts/OpenSans-Regular.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype/OpenSans-Regular.ttf'}} != {'/wok-ui.html': {'tools.wokauth.on': True}, '/favicon.ico': {'tools.staticfile.on': True, 'tools.staticfile.filename': '/home/danielhb/wok/ui/images/logo.ico'}, '/images': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticdir.dir': '/home/danielhb/wok/ui/images', 'tools.staticdir.on': True}, '/fonts/OpenSans-LightItalic.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype//OpenSans-LightItalic.ttf'}, '/base64/jquery.base64.js': {'tools.nocache.on': True, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/home/danielhb/wok/ui/base64/jquery.base64.js'}, '/fonts/OpenSans-Bold.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype//OpenSans-Bold.ttf'}, '/fonts/fontawesome-webfont.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype/fontawesome-webfont.ttf'}, '/js': {'tools.staticdir.dir': '/home/danielhb/wok/ui/js', 'tools.expires.on': True, 'tools.expires.secs': 31536000, 'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticdir.on': True}, '/robots.txt': {'tools.staticfile.on': True, 'tools.staticfile.filename': '/home/danielhb/wok/ui/robots.txt'}, '/': {'request.methods_with_bodies': ('POST', 'PUT'), 'tools.sessions.name': 'wok', 'tools.proxy.on': True, 'tools.sessions.locking': 'explicit', 'tools.sessions.httponly': True, 'tools.sessions.storage_type': 'ram', 'tools.sessions.on': True, 'tools.sessions.secure': True, 'tools.wokauth.on': False, 'tools.nocache.on': True, 'tools.trailing_slash.on': False}, '/fonts/OpenSans-ExtraBold.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype//OpenSans-ExtraBold.ttf'}, '/fonts/OpenSans-ExtraBoldItalic.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype//OpenSans-ExtraBoldItalic.ttf'}, '/fonts/OpenSans-Regular.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype//OpenSans-Regular.ttf'}, '/libs': {'tools.staticdir.dir': '/home/danielhb/wok/ui/libs', 'tools.expires.on': True, 'tools.expires.secs': 31536000, 'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticdir.on': True}, '/data/logs': {'tools.wokauth.on': True, 'tools.nocache.on': False, 'tools.staticdir.dir': '/home/danielhb/wok/data/logs', 'tools.staticdir.on': True}, '/fonts/OpenSans-Italic.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype//OpenSans-Italic.ttf'}, '/fonts/OpenSans-Semibold.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype//OpenSans-Semibold.ttf'}, '/ui/config/tab-ext.xml': {'tools.nocache.on': True, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/home/danielhb/wok/ui/config/tab-ext.xml'}, '/css': {'tools.staticdir.dir': '/home/danielhb/wok/ui/css', 'tools.expires.on': True, 'tools.expires.secs': 31536000, 'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticdir.on': True}, '/fonts/OpenSans-BoldItalic.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype//OpenSans-BoldItalic.ttf'}, '/help': {'tools.nocache.on': True, 'tools.staticdir.dir': '/home/danielhb/wok/ui/pages/help', 'tools.staticdir.on': True}, '/fonts/OpenSans-Light.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype//OpenSans-Light.ttf'}, '/fonts/OpenSans-SemiboldItalic.ttf': {'tools.wokauth.on': False, 'tools.nocache.on': False, 'tools.staticfile.on': True, 'tools.staticfile.filename': '/usr/share/fonts/truetype//OpenSans-SemiboldItalic.ttf'}}

----------------------------------------------------------------------
Ran 41 tests in 55.598s

FAILED (failures=1, skipped=2)
```

**Comment by biancafc** [comment]
CentOS (with/without sudo)
```
./run_tests.sh
WARNING: no 'numpy' module, HyBi protocol will be slower
Push server created on address /run/user/0/woknotifications
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bianca/kimchi-project-tests/wok/src/wok/websocket.py", line 96, in start_proxy
    server.start_server()
  File "/usr/lib/python2.7/site-packages/websockify/websocket.py", line 909, in start_server
    tcp_keepintvl=self.tcp_keepintvl)
  File "/usr/lib/python2.7/site-packages/websockify/websocket.py", line 698, in socket
    sock.bind(addrs[0][4])
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

libvirt: Test Driver error : Domain not found
libvirt: Test Driver error : Storage pool not found

*** Kimchi: Running feature tests ***
Run command: 'systemctl is-active libvirtd.service'
out:
active

Service Libvirtd running ...: True
Run command: 'systemctl is-active libvirtd.service'
out:
active

NFS Target Probe support ...: True
Fibre Channel Host support .: True
Run command: 'modprobe vfio-pci'
Kernel VFIO support ........: True
Run command: 'nmcli dev status'
out:
DEVICE      TYPE      STATE      CONNECTION
virbr0      bridge    connected  virbr0
ens33       ethernet  connected  ens33
ens37       ethernet  connected  Wired connection 1
ens38       ethernet  connected  Wired connection 2
ens39       ethernet  connected  Wired connection 3
lo          loopback  unmanaged  --
virbr0-nic  tun       unmanaged  --

Network Manager running ....: True
libvirt: Domain Config error : unsupported configuration: memory hotplug tunables <maxMemory> are not supported by this hypervisor driver
Memory Hotplug support .....: False
*** Kimchi: Feature tests completed ***

Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

libvirt: Node Device Driver error : this function is not supported by the connection driver: virConnectListAllNodeDevices
Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

libvirt: Test Driver error : Storage pool not found
Exception Storage pool not found occured when cleaning scan result
Run command: 'systemctl is-active libvirtd.service'
out:
active

libvirt: Node Device Driver error : this function is not supported by the connection driver: virConnectListAllNodeDevices
Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

libvirt: Node Device Driver error : this function is not supported by the connection driver: virConnectListAllNodeDevices
Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'firewall-cmd --state -q'
Run command: 'systemctl is-active libvirtd.service'
out:
active

libvirt: Node Device Driver error : this function is not supported by the connection driver: virConnectListAllNodeDevices
Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

libvirt: Node Device Driver error : this function is not supported by the connection driver: virConnectListAllNodeDevices
Run command: 'systemctl is-active libvirtd.service'
out:
active

Run command: 'systemctl is-active libvirtd.service'
out:
active

Cannot upgrade objectstore schema: no such table: objects
Error while upgrading objectstore data: no such table: objects
KCHUTILS0006E: KCHUTILS0006E
Failed to import plugin plugins.kimchi.Kimchi, error: KCHUTILS0006E: KCHUTILS0006E
Run command: 'tuned-adm active'
out:
Current active profile: virtual-guest

Cannot upgrade objectstore schema: no such table: objects
*** Ginger Base: Running capabilities tests ***
System Report Tool ...: True
Logging YumUpdate features.
Impossible to execute 'zypper --help'
System Update Tool ...: True
Repo Management Tool .: yum
*** Ginger Base: Capabilities tests completed ***
[20/Mar/2017:10:55:30] ENGINE Bus STARTING
Frus __init
[20/Mar/2017:10:55:30] ENGINE Started monitor thread 'Autoreloader'.
[20/Mar/2017:10:55:35] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x16a9650>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 197, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 151, in start
    ServerAdapter.start(self)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 167, in start
    wait_for_free_port(*self.bind_addr)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 410, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 8010 not free on '127.0.0.1'


*** Kimchi: Running dependable feature tests ***
Run command: 'systemctl is-active libvirtd.service'
out:
active

QEMU stream support .......: True
Libvirt Stream Protocols ..: ['http', 'https', 'ftp', 'ftps', 'tftp']
*** Kimchi: Dependable feature tests completed ***

[20/Mar/2017:10:55:35] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 235, in start
    self.publish('start')
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 215, in publish
    raise exc
ChannelFailures: IOError("Port 8010 not free on '127.0.0.1'",)

[20/Mar/2017:10:55:35] ENGINE Bus STOPPING
[20/Mar/2017:10:55:35] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8010)) already shut down
Run command: 'systemctl is-active libvirtd.service'
out:
active

libvirt: Test Driver error : Domain not found
libvirt: Test Driver error : Storage pool not found
[20/Mar/2017:10:55:35] ENGINE Stopped thread 'Autoreloader'.
[20/Mar/2017:10:55:35] ENGINE Bus STOPPED
[20/Mar/2017:10:55:35] ENGINE Bus EXITING
Closing any VNC/SPICE firewall ports opened by Kimchi ...
[20/Mar/2017:10:55:35] ENGINE Bus EXITED
make[3]: *** [check-local] Error 70
make[3]: Leaving directory `/home/bianca/kimchi-project-tests/wok/tests'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/home/bianca/kimchi-project-tests/wok/tests'
make[1]: *** [check] Error 2
make[1]: Leaving directory `/home/bianca/kimchi-project-tests/wok/tests'
make: *** [check-recursive] Error 1
```
