### ISSUE TITLE
Wok fails to start with Cherrypy 12.0

### ISSUE THREAD

**Issue by mASOUDd** [kimchi-project/wok#234]
Cherrypy 12.0 removed support for "engine.timeout_monitor.on" config option as stated in the [release change notes](https://github.com/cherrypy/cherrypy/blob/c17be0f9c42bbce95b37688dd548e47114f4a136/CHANGES.rst#v1200)

wokd crashes with this output:
`Traceback (most recent call last):
  File "/usr/bin/wokd", line 93, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/wokd", line 90, in main
    wok.server.main(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 190, in main
    srv = Server(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 92, in __init__
    cherrypy.engine.timeout_monitor.unsubscribe()
AttributeError: 'Bus' object has no attribute 'timeout_monitor'
`

**Comment by chr0mag** [comment]
Commenting out the offending line gets one past this.  The following _sed_ command will allow you to do this from a build script until a more permanent fix is added:

`sed --in-place 's/cherrypy.engine.timeout_monitor.unsubscribe()/#cherrypy.engine.timeout_monitor.unsubscribe()/' src/wok/server.py`
