### ISSUE TITLE
Wok.d service won't start after update (Ubuntu 16)

### ISSUE THREAD

**Issue by wintermute000** [kimchi-project/wok#258]
Not sure how it happened, but at some stage, wokd.service stopped starting. All dependencies are installed and it WAS all working formerly. Ubuntu 16.04
```

Dec 13 21:24:26 ******* systemd[1]: Started Wok - Webserver Originated from Kimchi.
Dec 13 21:24:27 ******* wokd[1708]: Traceback (most recent call last):
Dec 13 21:24:27 ******* wokd[1708]:   File "/usr/bin/wokd", line 30, in <module>
Dec 13 21:24:27 ******* wokd[1708]:     import wok.server
Dec 13 21:24:27 ******* wokd[1708]:   File "/usr/lib/python2.7/dist-packages/wok/server.py", line 23, in <module>
Dec 13 21:24:27 ******* wokd[1708]:     import cherrypy
Dec 13 21:24:27 ******* wokd[1708]:   File "/usr/local/lib/python2.7/dist-packages/cherrypy/__init__.py", line 73, in <module>
Dec 13 21:24:27 ******* wokd[1708]:     from ._cptools import default_toolbox as tools, Tool
Dec 13 21:24:27 ******* wokd[1708]:   File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cptools.py", line 33, in <module>
Dec 13 21:24:27 ******* wokd[1708]:     from cherrypy.lib import auth_basic, auth_digest
Dec 13 21:24:27 ******* wokd[1708]:   File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/auth_digest.py", line 27, in <module>
Dec 13 21:24:27 ******* wokd[1708]:     from six.moves.urllib.request import parse_http_list, parse_keqv_list
Dec 13 21:24:27 ******* wokd[1708]: ImportError: cannot import name parse_http_list
Dec 13 21:24:27 ******* systemd[1]: wokd.service: Main process exited, code=exited, status=1/FAILURE
Dec 13 21:24:27 ******* systemd[1]: wokd.service: Unit entered failed state.
Dec 13 21:24:27 ******* systemd[1]: wokd.service: Failed with result 'exit-code'.

# dpkg -l *six
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                         Version                     Architecture                Description
+++-============================================-===========================-===========================-=============================================================================================
ii  pypy-six                                     1.10.0-3                    all                         Python 2 and 3 compatibility library (PyPy interface)
ii  python-six                                   1.10.0-3                    all                         Python 2 and 3 compatibility library (Python 2 interface)
ii  python3-six                                  1.10.0-3                    all                         Python 2 and 3 compatibility library (Python 3 interface)
```

**Comment by wintermute000** [comment]
# dpkg -l *six
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                         Version                     Architecture                Description
+++-============================================-===========================-===========================-=============================================================================================
ii  pypy-six                                     1.10.0-3                    all                         Python 2 and 3 compatibility library (PyPy interface)
ii  python-six                                   1.10.0-3                    all                         Python 2 and 3 compatibility library (Python 2 interface)
ii  python3-six                                  1.10.0-3                    all                         Python 2 and 3 compatibility library (Python 3 interface)

**Comment by alinefm** [comment]
Hi @wintermute000!

Usually I test Kimchi on the latest Ubuntu version. I will install a VM to give it a try.

In the main time, any reason to do not update it to Ubuntu 18.04 (LTS) ?
