### ISSUE TITLE
Curious missing dependency on websockify

### ISSUE THREAD

**Issue by khushil** [kimchi-project/wok#279]
I'm getting the following after following the instructions. The module is definitely installed...

root@viola:/etc/nginx/conf.d# service wokd status
● wokd.service - Wok - Webserver Originated from Kimchi
   Loaded: loaded (/lib/systemd/system/wokd.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/wokd.service.d
           └─kimchi.conf
   Active: failed (Result: exit-code) since Sat 2019-10-26 02:28:47 UTC; 9s ago
     Docs: https://github.com/kimchi-project/wok/wiki
  Process: 7930 ExecStart=/usr/bin/wokd (code=exited, status=1/FAILURE)
 Main PID: 7930 (code=exited, status=1/FAILURE)

Oct 26 02:28:47 viola wokd[7930]: Traceback (most recent call last):
Oct 26 02:28:47 viola wokd[7930]:   File "/usr/bin/wokd", line 30, in <module>
Oct 26 02:28:47 viola wokd[7930]:     import wok.server
Oct 26 02:28:47 viola wokd[7930]:   File "/usr/lib/python2.7/dist-packages/wok/server.py", line 28, in <module>
Oct 26 02:28:47 viola wokd[7930]:     from wok import auth, config, websocket
Oct 26 02:28:47 viola wokd[7930]:   File "/usr/lib/python2.7/dist-packages/wok/websocket.py", line 28, in <module>
Oct 26 02:28:47 viola wokd[7930]:     from websockify import WebSocketProxy
Oct 26 02:28:47 viola wokd[7930]: ImportError: No module named websockify
Oct 26 02:28:47 viola systemd[1]: wokd.service: Main process exited, code=exited, status=1/FAILURE
Oct 26 02:28:47 viola systemd[1]: wokd.service: Failed with result 'exit-code'.

**Comment by alinefm** [comment]
Hey @khushil 

could you try Wok 3.0? https://github.com/kimchi-project/wok/releases/tag/3.0.0
