### ISSUE TITLE
Can't run wokd

### ISSUE THREAD

**Issue by Alterjero** [kimchi-project/wok#280]
i follow Getting Started for install wok in https://github.com/kimchi-project/wok/#getting-started but i have

oct. 28 15:52:33 ubuntu wokd[40413]:     import wok.server
oct. 28 15:52:33 ubuntu wokd[40413]:   File "/usr/lib/python3.6/site-packages/wok/server.py", line 28, in <module>
oct. 28 15:52:33 ubuntu wokd[40413]:     from wok import auth
oct. 28 15:52:33 ubuntu wokd[40413]:   File "/usr/lib/python3.6/site-packages/wok/auth.py", line 38, in <module>
oct. 28 15:52:33 ubuntu wokd[40413]:     from wok import template
oct. 28 15:52:33 ubuntu wokd[40413]:   File "/usr/lib/python3.6/site-packages/wok/template.py", line 27, in <module>
oct. 28 15:52:33 ubuntu wokd[40413]:     from Cheetah.Template import Template
oct. 28 15:52:33 ubuntu wokd[40413]: ModuleNotFoundError: No module named 'Cheetah'
oct. 28 15:52:33 ubuntu systemd[1]: wokd.service: Main process exited, code=exited, status=1/FAILURE
oct. 28 15:52:33 ubuntu systemd[1]: wokd.service: Failed with result 'exit-code'.

please help

**Comment by Alterjero** [comment]
i try import Cheetah in pip3 but

sudo -E -H pip3 install python3-cheetah
Collecting python3-cheetah
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/python3-cheetah/

**Comment by Alterjero** [comment]
i try install kimchi with http://www.ubuntuboss.com/ubuntu-server-18-04-as-a-hypervisor-using-kvm-and-kimchi-for-vm-management/ and the other computer
and is good 
problème solve
