### ISSUE TITLE
Unable to start wok

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/wok#29]
Downloaded the latest upstreamed code.

wokd is not able start.

nginx: [emerg] still could not bind()
Traceback (most recent call last):
  File "/usr/bin/wokd", line 97, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/wokd", line 94, in main
    wok.server.main(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 204, in main
    srv = Server(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 137, in __init__
    self._load_plugins(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 182, in _load_plugins
    for ident, node in sub_nodes.items():
UnboundLocalError: local variable 'sub_nodes' referenced before assignment

**Comment by alinefm** [comment]
Fixed by 382ce1938b0d41a3549b61985823311baa628310
