### ISSUE TITLE
Fedora32: cant start wokd  - ModuleNotFoundError: No module named 'Cheetah

### ISSUE THREAD

**Issue by infraengineer-sre** [kimchi-project/wok#307]
**Run with Python**
```
sudo python3 src/wokd
Traceback (most recent call last):
  File "src/wokd", line 30, in <module>
    import wok.server
  File "/tmp/wok/src/wok/server.py", line 28, in <module>
    from wok import auth
  File "/tmp/wok/src/wok/auth.py", line 38, in <module>
    from wok import template
  File "/tmp/wok/src/wok/template.py", line 27, in <module>
    from Cheetah.Template import Template
ModuleNotFoundError: No module named 'Cheetah
```

**To Reproduce**
Build from source

`wok-3.0.0-3.git25c5b2a8.fc32.noarch`

```
systemctl start wokd

systemctl status wokd
● wokd.service - Wok - Webserver Originated from Kimchi
     Loaded: loaded (/usr/lib/systemd/system/wokd.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/wokd.service.d
             └─kimchi.conf
     Active: failed (Result: exit-code) since Tue 2020-09-22 20:42:37 MSK; 2s ago
       Docs: https://github.com/kimchi-project/wok/wiki
    Process: 1826294 ExecStart=/usr/bin/wokd (code=exited, status=1/FAILURE)
   Main PID: 1826294 (code=exited, status=1/FAILURE)
        CPU: 464ms

Sep 22 20:42:37 localhost.localdomain wokd[1826294]:     import wok.server
Sep 22 20:42:37 localhost.localdomain wokd[1826294]:   File "/usr/lib/python3.8/site-packages/wok/server.py", line 28, in <module>
Sep 22 20:42:37 localhost.localdomain wokd[1826294]:     from wok import auth
Sep 22 20:42:37 localhost.localdomain wokd[1826294]:   File "/usr/lib/python3.8/site-packages/wok/auth.py", line 38, in <module>
Sep 22 20:42:37 localhost.localdomain wokd[1826294]:     from wok import template
Sep 22 20:42:37 localhost.localdomain wokd[1826294]:   File "/usr/lib/python3.8/site-packages/wok/template.py", line 27, in <module>
```

**System**
 - OS: Fedora release 32 (Thirty Two)
 - Linux 5.8.4-200.fc32.x86_64 #1 SMP Wed Aug 26 22:28:08 UTC 2020 x86_64

**Comment by nrdmtt** [comment]
Do you have python3-cheetah python-cheetah and installed?

**Comment by BiatuAutMiahn** [comment]
I think the README.md should indicate python3-cheetah and nginx as deps
